#!/bin/bash
echo "[*] Checking repository status"
git status &&
echo "[*] Adding untracked files"
git add . && 
echo "[*] Committing changes to local"
git commit -am "Regular changes" &&
echo "[*] Pushing changes to remote"
git push origin main && 
echo "[*] Updating local"
git pull origin main